## Import all Vendor Bundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

## Application ROutes
root:
    path:      "/"
    defaults:  { _controller: SubspaceCustomerBundle:Default:index }

locations:
    path:      "/locations"
    defaults:  { _controller: SubspaceCustomerBundle:Default:locations }

tour:
    path:      "/tour"
    defaults:  { _controller: SubspaceCustomerBundle:Default:tour }

pricing:
    path:      "/pricing"
    defaults:  { _controller: SubspaceCustomerBundle:Default:pricing }

signup:
    path:      "/signup"
    defaults:  { _controller: SubspaceCustomerBundle:Default:signup }

forgottenpassword:
    path:      "/forgottenpassword"
    defaults:  { _controller: SubspaceCustomerBundle:Default:forgottenpassword }

resetpassword:
    path:      "/resetpassword"
    defaults:  { _controller: SubspaceCustomerBundle:Default:resetpassword }

profile:
    path:      "/profile"
    defaults:  { _controller: SubspaceCustomerBundle:Default:profile }

listings:
    path:      "/listings"
    defaults:  { _controller: SubspaceCustomerBundle:Default:listings }

editlisting:
    path:      "/editlisting"
    defaults:  { _controller: SubspaceCustomerBundle:Default:editlisting }