root:
    path:      "/"
    defaults:  { _controller: SubspaceCustomerBundle:Default:index }

locations:
    path:      "/locations"
    defaults:  { _controller: SubspaceCustomerBundle:Default:locations }

tour:
    path:      "/tour"
    defaults:  { _controller: SubspaceCustomerBundle:Default:tour }

pricing:
    path:      "/pricing"
    defaults:  { _controller: SubspaceCustomerBundle:Default:pricing }

login:
    path:      "/login"
    defaults:  { _controller: SubspaceCustomerBundle:Default:login }

signup:
    path:      "/signup"
    defaults:  { _controller: SubspaceCustomerBundle:Default:signup }